import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const p = await (await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true })).newPage();
p.on('console', m => console.log('CONSOLE', m.type(), m.text()));
p.on('pageerror', e => console.log('PAGEERROR', e.message));
p.on('requestfailed', r => console.log('REQFAIL', r.url(), r.failure()?.errorText));
p.on('response', r => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
await p.goto(process.env.URL, { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
console.log('__game?', await p.evaluate(() => typeof window.__game));
console.log('script src:', await p.evaluate(() => [...document.querySelectorAll('script')].map(s => s.src)));
await b.close();
